name: Python CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Suma
      run:
        python -m unittest tests/test_suma.py

    - name: Resta
      run:     
        python -m unittest tests/test_resta.py

    - name: Multiplicacion
      run:    
        python -m unittest tests/test_multiplicacion.py
        
    - name: Division
      run:    
        python -m unittest tests/test_division.py
